# .github/workflows/demo.yml

name: CI
on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Run a one-line script
              run: echo Hello, world!
